apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /?alb
spec:
  type: {{.Values.service.type}}
  ports:
    - name: http
      port: {{.Values.service.port}}
      targetPort: {{.Values.containerPort}}
      protocol: TCP
  selector:
    app: {{.Values.name}}
