apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kustomize overlay
images:
- name: overlay-image
  newName: 580214777026.dkr.ecr.ap-southeast-1.amazonaws.com/kr-partner-app-dev
  newTag: example2

helmGlobals:
  chartHome: ../../helm
# CustomResourceDefinition 이 있을 경우 true
  # name 은 helm 폴더 하위의 helm 폴더 이름과 직결된다.
helmCharts:
- includeCRDs: true
  name: backend
  namespace: default
  releaseName: inho-api
  valuesFile: values.yaml
  version: 1.0.0
